apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ovms-client
  name: ovms-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: ovms-client
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/stable-df-helm-default: "true"
        io.kompose.service: ovms-client
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name}}
      serviceAccount: {{ .Values.serviceAccount.name}}
      containers:
        - name: ovms-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python3", "face_detection.py", "--batch_size", "1", "--width", "300", "--height", "300", "--output_dir", "results","--grpc_address", "server-service", "--grpc_port", "9000"]
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: ovms-client-claim0
      restartPolicy: OnFailure
      volumes:
        - name: ovms-client-claim0
          persistentVolumeClaim:
            claimName: ovms-client-claim0
